"""removing availability zone id

Revision ID: 8eab157fd45a
Revises: 8222ad44d910
Create Date: 2022-08-05 04:06:08.800885

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "8eab157fd45a"
down_revision = "8222ad44d910"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("cars_availability_zone_id_fkey", "cars", type_="foreignkey")
    op.drop_column("cars", "availability_zone_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "cars",
        sa.Column(
            "availability_zone_id",
            sa.INTEGER(),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.create_foreign_key(
        "cars_availability_zone_id_fkey",
        "cars",
        "car_availability_zones",
        ["availability_zone_id"],
        ["id"],
    )
    # ### end Alembic commands ###
